// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Users.Infrastructure.Db;

#nullable disable

namespace Users.Infrastructure.Migrations;

[DbContext(typeof(UserDbContext))]
[Migration("20251214071204_AdminUserRoleSeeder")]
partial class AdminUserRoleSeeder
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("Users.Domain.Entities.Menu", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CreatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Created_By");

                b.Property<DateTime>("CreatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Created_Time");

                b.Property<string>("Icon")
                    .HasColumnType("longtext")
                    .HasColumnName("Icon");

                b.Property<bool>("IsActive")
                    .HasColumnType("tinyint(1)")
                    .HasColumnName("Is_Active");

                b.Property<string>("LastUpdatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Last_Updated_By");

                b.Property<DateTime>("LastUpdatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Last_Updated_Time");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)")
                    .HasColumnName("Name");

                b.Property<int?>("ParentId")
                    .HasColumnType("int")
                    .HasColumnName("Parent_Id");

                b.Property<string>("Route")
                    .HasColumnType("longtext")
                    .HasColumnName("Route");

                b.Property<int>("Sequence")
                    .HasColumnType("int")
                    .HasColumnName("Sequence");

                b.HasKey("Id");

                b.HasIndex("ParentId");

                b.ToTable("tbl_Users_Menus", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Profile",
                        Route = "#",
                        Sequence = 1
                    },
                    new
                    {
                        Id = 2,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Masters",
                        Route = "#",
                        Sequence = 2
                    },
                    new
                    {
                        Id = 3,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Users",
                        Route = "#",
                        Sequence = 3
                    },
                    new
                    {
                        Id = 9,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "View Profile",
                        ParentId = 1,
                        Route = "/admin/dashboard/masters/menus",
                        Sequence = 1
                    },
                    new
                    {
                        Id = 10,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Change Password",
                        ParentId = 1,
                        Route = "/admin/dashboard/masters/menus",
                        Sequence = 2
                    },
                    new
                    {
                        Id = 4,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Countries",
                        ParentId = 2,
                        Route = "/admin/masters/countries",
                        Sequence = 1
                    },
                    new
                    {
                        Id = 5,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "States",
                        ParentId = 2,
                        Route = "/admin/masters/states",
                        Sequence = 2
                    },
                    new
                    {
                        Id = 6,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Cities",
                        ParentId = 2,
                        Route = "/admin/masters/cities",
                        Sequence = 3
                    },
                    new
                    {
                        Id = 7,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Roles",
                        ParentId = 2,
                        Route = "/admin/masters/roles",
                        Sequence = 4
                    },
                    new
                    {
                        Id = 8,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Menus",
                        ParentId = 2,
                        Route = "/admin/masters/menus",
                        Sequence = 5
                    },
                    new
                    {
                        Id = 11,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Users",
                        ParentId = 3,
                        Route = "/admin/user-management/all-users",
                        Sequence = 1
                    },
                    new
                    {
                        Id = 12,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Approve Users",
                        ParentId = 3,
                        Route = "/admin/user-management/approve-user",
                        Sequence = 2
                    },
                    new
                    {
                        Id = 13,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Unlock Users",
                        ParentId = 3,
                        Route = "/admin/user-management/unlock-user",
                        Sequence = 3
                    },
                    new
                    {
                        Id = 14,
                        CreatedBy = "Admin",
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Assign Roles",
                        ParentId = 3,
                        Route = "/admin/user-management/assign-roles",
                        Sequence = 4
                    });
            });

        modelBuilder.Entity("Users.Domain.Entities.Role", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CreatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Created_By");

                b.Property<DateTime>("CreatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Created_Time");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasColumnName("Description");

                b.Property<bool>("IsActive")
                    .HasColumnType("tinyint(1)")
                    .HasColumnName("Is_Active");

                b.Property<string>("LastUpdatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Last_Updated_By");

                b.Property<DateTime>("LastUpdatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Last_Updated_Time");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasColumnName("Name");

                b.HasKey("Id");

                b.ToTable("tbl_Users_Roles", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Description = "Platform administrator",
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Admin"
                    },
                    new
                    {
                        Id = 2,
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Description = "Internal employee",
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Employee"
                    },
                    new
                    {
                        Id = 3,
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Description = "Car dealer",
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Dealer"
                    },
                    new
                    {
                        Id = 4,
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Description = "Bank representative",
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Banker"
                    },
                    new
                    {
                        Id = 5,
                        CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Description = "End customer",
                        IsActive = true,
                        LastUpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Customer"
                    });
            });

        modelBuilder.Entity("Users.Domain.Entities.RoleMenu", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CreatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Created_By");

                b.Property<DateTime>("CreatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Created_Time");

                b.Property<string>("LastUpdatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Last_Updated_By");

                b.Property<DateTime>("LastUpdatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Last_Updated_Time");

                b.Property<int>("MenuId")
                    .HasColumnType("int")
                    .HasColumnName("Menu_Id");

                b.Property<int>("RoleId")
                    .HasColumnType("int")
                    .HasColumnName("Role_Id");

                b.HasKey("Id");

                b.HasIndex("MenuId");

                b.HasIndex("RoleId");

                b.ToTable("tbl_Users_Role_Menus");
            });

        modelBuilder.Entity("Users.Domain.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasColumnName("Address");

                b.Property<int>("CityId")
                    .HasColumnType("int")
                    .HasColumnName("City_Id");

                b.Property<int>("CountryId")
                    .HasColumnType("int")
                    .HasColumnName("Country_Id");

                b.Property<string>("CreatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Created_By");

                b.Property<DateTime>("CreatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Created_Time");

                b.Property<DateOnly>("DateOfBirth")
                    .HasColumnType("date")
                    .HasColumnName("Date_Of_Birth");

                b.Property<string>("DeviceTokensJson")
                    .HasColumnType("longtext")
                    .HasColumnName("Device_Tokens_Json");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("Email");

                b.Property<bool>("EmailVerified")
                    .HasColumnType("tinyint(1)")
                    .HasColumnName("Email_Verified");

                b.Property<int>("FailedLoginCount")
                    .HasColumnType("int")
                    .HasColumnName("Failed_Login_Count");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasColumnName("First_Name");

                b.Property<int>("Gender")
                    .HasColumnType("int")
                    .HasColumnName("Gender");

                b.Property<bool>("IsActive")
                    .HasColumnType("tinyint(1)")
                    .HasColumnName("Is_Active");

                b.Property<bool>("IsApproved")
                    .HasColumnType("tinyint(1)")
                    .HasColumnName("Is_Approved");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasColumnName("Last_Name");

                b.Property<string>("LastUpdatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Last_Updated_By");

                b.Property<DateTime>("LastUpdatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Last_Updated_Time");

                b.Property<DateTime?>("LockoutEndAt")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Lockout_End_At");

                b.Property<bool>("MfaEnabled")
                    .HasColumnType("tinyint(1)")
                    .HasColumnName("Mfa_Enabled");

                b.Property<string>("MfaSecret")
                    .HasColumnType("longtext")
                    .HasColumnName("Mfa_Secret");

                b.Property<string>("MiddleName")
                    .HasColumnType("longtext")
                    .HasColumnName("Middle_Name");

                b.Property<string>("Mobile")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasColumnName("Mobile");

                b.Property<bool>("MobileVerified")
                    .HasColumnType("tinyint(1)")
                    .HasColumnName("Mobile_Verified");

                b.Property<DateTime?>("PasswordExpiryDate")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Password_Expiry_Date");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasColumnName("Password_Hash");

                b.Property<DateTime>("PasswordLastChanged")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Password_Last_Changed");

                b.Property<string>("PinCode")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasColumnName("Pin_Code");

                b.Property<string>("ProfileImageUrl")
                    .HasColumnType("longtext")
                    .HasColumnName("Profile_Image_Url");

                b.Property<int>("StateId")
                    .HasColumnType("int")
                    .HasColumnName("State_Id");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasColumnType("longtext")
                    .HasColumnName("User_Name");

                b.HasKey("Id");

                b.ToTable("tbl_Users_Users", (string)null);
            });

        modelBuilder.Entity("Users.Domain.Entities.UserRole", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CreatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Created_By");

                b.Property<DateTime>("CreatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Created_Time");

                b.Property<string>("LastUpdatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Last_Updated_By");

                b.Property<DateTime>("LastUpdatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Last_Updated_Time");

                b.Property<int>("RoleId")
                    .HasColumnType("int")
                    .HasColumnName("Role_Id");

                b.Property<int>("UserId")
                    .HasColumnType("int")
                    .HasColumnName("User_Id");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.HasIndex("UserId", "RoleId")
                    .IsUnique();

                b.ToTable("tbl_Users_UserRoles", (string)null);
            });

        modelBuilder.Entity("Users.Domain.Entities.Menu", b =>
            {
                b.HasOne("Users.Domain.Entities.Menu", "Parent")
                    .WithMany("Children")
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Parent");
            });

        modelBuilder.Entity("Users.Domain.Entities.RoleMenu", b =>
            {
                b.HasOne("Users.Domain.Entities.Menu", "Menu")
                    .WithMany("RoleMenus")
                    .HasForeignKey("MenuId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Users.Domain.Entities.Role", "Role")
                    .WithMany("RoleMenus")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Menu");

                b.Navigation("Role");
            });

        modelBuilder.Entity("Users.Domain.Entities.UserRole", b =>
            {
                b.HasOne("Users.Domain.Entities.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Users.Domain.Entities.User", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });

        modelBuilder.Entity("Users.Domain.Entities.Menu", b =>
            {
                b.Navigation("Children");

                b.Navigation("RoleMenus");
            });

        modelBuilder.Entity("Users.Domain.Entities.Role", b =>
            {
                b.Navigation("RoleMenus");

                b.Navigation("UserRoles");
            });

        modelBuilder.Entity("Users.Domain.Entities.User", b =>
            {
                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
    }
}
