// <auto-generated />
using System;
using Location.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Location.Infrastructure.Migrations;

[DbContext(typeof(LocationDbContext))]
partial class LocationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("Location.Domain.Entities.City", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CreatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Created_By");

                b.Property<DateTime>("CreatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Created_Time");

                b.Property<string>("LastUpdatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Last_Updated_By");

                b.Property<DateTime>("LastUpdatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Last_Updated_Time");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)")
                    .HasColumnName("Name");

                b.Property<int>("StateId")
                    .HasColumnType("int")
                    .HasColumnName("State_Id");

                b.HasKey("Id");

                b.HasIndex("StateId");

                b.ToTable("tbl_Location_Cities", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Mumbai",
                        StateId = 1
                    },
                    new
                    {
                        Id = 2,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Pune",
                        StateId = 1
                    },
                    new
                    {
                        Id = 3,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Bengaluru",
                        StateId = 2
                    });
            });

        modelBuilder.Entity("Location.Domain.Entities.Country", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CreatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Created_By");

                b.Property<DateTime>("CreatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Created_Time");

                b.Property<string>("IsoCode")
                    .IsRequired()
                    .HasMaxLength(5)
                    .HasColumnType("varchar(5)")
                    .HasColumnName("Iso_Code");

                b.Property<string>("LastUpdatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Last_Updated_By");

                b.Property<DateTime>("LastUpdatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Last_Updated_Time");

                b.Property<string>("MobileCode")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("Mobile_Code");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)")
                    .HasColumnName("Name");

                b.HasKey("Id");

                b.ToTable("tbl_Location_Countries", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AF",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+93",
                        Name = "Afghanistan"
                    },
                    new
                    {
                        Id = 2,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AL",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+355",
                        Name = "Albania"
                    },
                    new
                    {
                        Id = 3,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "DZ",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+213",
                        Name = "Algeria"
                    },
                    new
                    {
                        Id = 4,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AD",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+376",
                        Name = "Andorra"
                    },
                    new
                    {
                        Id = 5,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AO",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+244",
                        Name = "Angola"
                    },
                    new
                    {
                        Id = 6,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AG",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+1268",
                        Name = "Antigua and Barbuda"
                    },
                    new
                    {
                        Id = 7,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AR",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+54",
                        Name = "Argentina"
                    },
                    new
                    {
                        Id = 8,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AM",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+374",
                        Name = "Armenia"
                    },
                    new
                    {
                        Id = 9,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AU",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+61",
                        Name = "Australia"
                    },
                    new
                    {
                        Id = 10,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AT",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+43",
                        Name = "Austria"
                    },
                    new
                    {
                        Id = 11,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "AZ",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+994",
                        Name = "Azerbaijan"
                    },
                    new
                    {
                        Id = 12,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BS",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+1242",
                        Name = "Bahamas"
                    },
                    new
                    {
                        Id = 13,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BH",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+973",
                        Name = "Bahrain"
                    },
                    new
                    {
                        Id = 14,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BD",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+880",
                        Name = "Bangladesh"
                    },
                    new
                    {
                        Id = 15,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BB",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+1246",
                        Name = "Barbados"
                    },
                    new
                    {
                        Id = 16,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BY",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+375",
                        Name = "Belarus"
                    },
                    new
                    {
                        Id = 17,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BE",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+32",
                        Name = "Belgium"
                    },
                    new
                    {
                        Id = 18,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BZ",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+501",
                        Name = "Belize"
                    },
                    new
                    {
                        Id = 19,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BJ",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+229",
                        Name = "Benin"
                    },
                    new
                    {
                        Id = 20,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BT",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+975",
                        Name = "Bhutan"
                    },
                    new
                    {
                        Id = 21,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BO",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+591",
                        Name = "Bolivia"
                    },
                    new
                    {
                        Id = 22,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BA",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+387",
                        Name = "Bosnia and Herzegovina"
                    },
                    new
                    {
                        Id = 23,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BW",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+267",
                        Name = "Botswana"
                    },
                    new
                    {
                        Id = 24,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BR",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+55",
                        Name = "Brazil"
                    },
                    new
                    {
                        Id = 25,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "BN",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+673",
                        Name = "Brunei Darussalam"
                    },
                    new
                    {
                        Id = 75,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "IN",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+91",
                        Name = "India"
                    },
                    new
                    {
                        Id = 184,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "US",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+1",
                        Name = "United States of America"
                    },
                    new
                    {
                        Id = 183,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsoCode = "GB",
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        MobileCode = "+44",
                        Name = "United Kingdom"
                    });
            });

        modelBuilder.Entity("Location.Domain.Entities.State", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CountryId")
                    .HasColumnType("int")
                    .HasColumnName("Country_Id");

                b.Property<string>("CreatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Created_By");

                b.Property<DateTime>("CreatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Created_Time");

                b.Property<string>("LastUpdatedBy")
                    .HasColumnType("longtext")
                    .HasColumnName("Last_Updated_By");

                b.Property<DateTime>("LastUpdatedTime")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Last_Updated_Time");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)")
                    .HasColumnName("Name");

                b.HasKey("Id");

                b.HasIndex("CountryId");

                b.ToTable("tbl_Location_States", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        CountryId = 75,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Maharashtra"
                    },
                    new
                    {
                        Id = 2,
                        CountryId = 75,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Karnataka"
                    },
                    new
                    {
                        Id = 3,
                        CountryId = 75,
                        CreatedBy = "Seeder",
                        CreatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        LastUpdatedBy = "Seeder",
                        LastUpdatedTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Name = "Tamil Nadu"
                    });
            });

        modelBuilder.Entity("Location.Domain.Entities.City", b =>
            {
                b.HasOne("Location.Domain.Entities.State", "State")
                    .WithMany("Cities")
                    .HasForeignKey("StateId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("State");
            });

        modelBuilder.Entity("Location.Domain.Entities.State", b =>
            {
                b.HasOne("Location.Domain.Entities.Country", "Country")
                    .WithMany("States")
                    .HasForeignKey("CountryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Country");
            });

        modelBuilder.Entity("Location.Domain.Entities.Country", b =>
            {
                b.Navigation("States");
            });

        modelBuilder.Entity("Location.Domain.Entities.State", b =>
            {
                b.Navigation("Cities");
            });
#pragma warning restore 612, 618
    }
}
