// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Infrastructure.Db;

#nullable disable

namespace Notification.Infrastructure.Migrations;

[DbContext(typeof(NotificationDbContext))]
[Migration("20251225091012_InitialCreateNotification")]
partial class InitialCreateNotification
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("Notification.Domain.Entities.UserNotification", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("Id");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ActionType")
                    .HasColumnType("int")
                    .HasColumnName("Action_Type");

                b.Property<int>("Category")
                    .HasColumnType("int")
                    .HasColumnName("Category");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("Created_At");

                b.Property<bool>("IsRead")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false)
                    .HasColumnName("Is_Read");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("varchar(1000)")
                    .HasColumnName("Message");

                b.Property<int?>("ReferenceId")
                    .HasColumnType("int")
                    .HasColumnName("Reference_Id");

                b.Property<int>("ReferenceType")
                    .HasColumnType("int")
                    .HasColumnName("Reference_Type");

                b.Property<int>("Severity")
                    .HasColumnType("int")
                    .HasColumnName("Severity");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)")
                    .HasColumnName("Title");

                b.Property<int>("UserId")
                    .HasColumnType("int")
                    .HasColumnName("User_Id");

                b.HasKey("Id");

                b.HasIndex("UserId", "IsRead");

                b.ToTable("tbl_Notification_UserNotifications", (string)null);
            });
#pragma warning restore 612, 618
    }
}
